### ISSUE TITLE
Add cryptosuites `eddsa-rdfc-2022` and `eddsa-jcs-2022`

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/eddsa-2022-cryptosuite#4]
The current implementation mostly matches the upcoming standard, but the standard changed its name to `eddsa-rdfc-2022` and uses a new data integrity v2 context. We should allow backwards compatible usage of `eddsa-2022` but also add the new name and context support. We should add JCS cryptosuite support as well or spin that off into its own library.

We could also deprecate this library and create an `eddsa-rdfc-2022` one and an `eddsa-jcs-2022` one -- and leave this library be. One way or another, we need to add the above capabilities.

See: https://github.com/w3c/vc-di-eddsa

**Comment by BigBlueHat** [comment]
It looks like this has partly happened via https://github.com/digitalbazaar/eddsa-rdfc-2022-cryptosuite correct?

**Comment by dlongley** [comment]
Yeah -- and the decision is that this library should be deprecated and no longer used.
